# Generated by Django 3.1.5 on 2021-07-12 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starsystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position_x', models.PositiveIntegerField()),
                ('position_y', models.PositiveIntegerField()),
                ('galaxy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='starsystem.galaxy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
