# Generated by Django 3.1.5 on 2021-07-12 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starsystem', '0003_star'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('diameter', models.PositiveIntegerField()),
                ('color', models.CharField(max_length=100)),
                ('live', models.BooleanField()),
                ('star_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='starsystem.starsystem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
